#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: A_MainMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass A_MainMenu.A_MainMenu_C
// 0x0008 (0x0378 - 0x0370)
class AA_MainMenu_C final : public ASBZLevelScriptMainMenuActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_A_MainMenu(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("A_MainMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"A_MainMenu_C")
	}
	static class AA_MainMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AA_MainMenu_C>();
	}
};

SDK_NAMESPACE_END
