#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Boquet_Destructible_01_C

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "Starbreeze_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Boquet_Destructible_01_C.BP_Boquet_Destructible_01_C_C
// 0x0018 (0x0340 - 0x0328)
class ABP_Boquet_Destructible_01_C_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USBZCosmeticDestructionComponent*       SBZCosmeticDestruction;                            // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_Boquet_Destructible_01_A_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature(ESBZCosmeticDestructionType Type, const struct FSBZCosmeticDestructionContext& HitContext);
	void ExecuteUbergraph_BP_Boquet_Destructible_01_C(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Boquet_Destructible_01_C_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Boquet_Destructible_01_C_C")
	}
	static class ABP_Boquet_Destructible_01_C_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Boquet_Destructible_01_C_C>();
	}
};

SDK_NAMESPACE_END
