#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Carried_Smartphone_OwnerNC

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Carried_Smartphone_OwnerNC.BP_Carried_Smartphone_OwnerNC_C
// 0x0038 (0x03A8 - 0x0370)
class ABP_Carried_Smartphone_OwnerNC_C final : public ASBZCarriedStaticInteractionActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          Box;                                               // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USBZOutlineComponent*                   SBZOutline_1;                                      // 0x0380(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USBZSensorComponent*                    SBZSensor;                                         // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USBZAIObjectiveComponent*               SBZAIObjective;                                    // 0x0390(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USBZOutlineComponent*                   SBZOutline;                                        // 0x0398(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x03A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_Carried_Smartphone_OwnerNC_Interactable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature(class USBZBaseInteractableComponent* Interactable_0, class USBZInteractorComponent* Interactor, bool bIsLocallyControlledInteractor);
	void ExecuteUbergraph_BP_Carried_Smartphone_OwnerNC(int32 EntryPoint);
	class USBZSensorComponent* GetSensorComponent();
	class USBZOutlineComponent* GetSensorOutlineComponent();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Carried_Smartphone_OwnerNC_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Carried_Smartphone_OwnerNC_C")
	}
	static class ABP_Carried_Smartphone_OwnerNC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Carried_Smartphone_OwnerNC_C>();
	}
};

SDK_NAMESPACE_END
