#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DAT_CodeBreaker_01_Interaction

#include "Basic.hpp"

#include "BP_DAT_CodeBreaker_01_Interaction_classes.hpp"
#include "BP_DAT_CodeBreaker_01_Interaction_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_DAT_CodeBreaker_01_Interaction.BP_DAT_CodeBreaker_01_Interaction_C.BndEvt__BP_ElevatorDoor_ControlPanel_InteractableComponent_K2Node_ComponentBoundEvent_2_SBZOnInteractableStateChangedDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class USBZBaseInteractableComponent*InteractableComponent_0                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    bInNewState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DAT_CodeBreaker_01_Interaction_C::BndEvt__BP_ElevatorDoor_ControlPanel_InteractableComponent_K2Node_ComponentBoundEvent_2_SBZOnInteractableStateChangedDelegate__DelegateSignature(const class USBZBaseInteractableComponent* InteractableComponent_0, bool bInNewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DAT_CodeBreaker_01_Interaction_C", "BndEvt__BP_ElevatorDoor_ControlPanel_InteractableComponent_K2Node_ComponentBoundEvent_2_SBZOnInteractableStateChangedDelegate__DelegateSignature");

	Params::BP_DAT_CodeBreaker_01_Interaction_C_BndEvt__BP_ElevatorDoor_ControlPanel_InteractableComponent_K2Node_ComponentBoundEvent_2_SBZOnInteractableStateChangedDelegate__DelegateSignature Parms{};

	Parms.InteractableComponent_0 = InteractableComponent_0;
	Parms.bInNewState = bInNewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DAT_CodeBreaker_01_Interaction.BP_DAT_CodeBreaker_01_Interaction_C.ExecuteUbergraph_BP_DAT_CodeBreaker_01_Interaction
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DAT_CodeBreaker_01_Interaction_C::ExecuteUbergraph_BP_DAT_CodeBreaker_01_Interaction(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DAT_CodeBreaker_01_Interaction_C", "ExecuteUbergraph_BP_DAT_CodeBreaker_01_Interaction");

	Params::BP_DAT_CodeBreaker_01_Interaction_C_ExecuteUbergraph_BP_DAT_CodeBreaker_01_Interaction Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DAT_CodeBreaker_01_Interaction.BP_DAT_CodeBreaker_01_Interaction_C.TurnOff
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_DAT_CodeBreaker_01_Interaction_C::TurnOff()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DAT_CodeBreaker_01_Interaction_C", "TurnOff");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DAT_CodeBreaker_01_Interaction.BP_DAT_CodeBreaker_01_Interaction_C.TurnOn
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_DAT_CodeBreaker_01_Interaction_C::TurnOn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DAT_CodeBreaker_01_Interaction_C", "TurnOn");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
