#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DesktopComputer_01_Monitor_GoldSharke

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_structs.hpp"
#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DesktopComputer_01_Monitor_GoldSharke.BP_DesktopComputer_01_Monitor_GoldSharke_C
// 0x0018 (0x0370 - 0x0358)
class ABP_DesktopComputer_01_Monitor_GoldSharke_C final : public ASBZSmallCosmeticDestruction
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0358(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USBZCosmeticDestructionComponent*       SBZCosmeticDestruction_1;                          // 0x0360(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	int32                                         DAmage_Taken;                                      // 0x0368(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          is_destructable;                                   // 0x036C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_CashRegister_01_Monitor_SmallDestruction_SBZCosmeticDestruction_1_K2Node_ComponentBoundEvent_5_SBZCosmeticDestructionComponenteSignature__DelegateSignature(ESBZCosmeticDestructionType Type, const struct FSBZCosmeticDestructionContext& HitContext);
	void ExecuteUbergraph_BP_DesktopComputer_01_Monitor_GoldSharke(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DesktopComputer_01_Monitor_GoldSharke_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DesktopComputer_01_Monitor_GoldSharke_C")
	}
	static class ABP_DesktopComputer_01_Monitor_GoldSharke_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DesktopComputer_01_Monitor_GoldSharke_C>();
	}
};

SDK_NAMESPACE_END
