#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EMPTrap_TEST

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"
#include "AkAudio_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_EMPTrap_TEST.BP_EMPTrap_TEST_C
// 0x0048 (0x03B8 - 0x0370)
class ABP_EMPTrap_TEST_C final : public ASBZReplicatedIntStateActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USBZAIObjectiveComponent*               SBZAIObjective;                                    // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USBZInteractableComponent*              SBZInteractable;                                   // 0x0380(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USBZOutlineComponent*                   SBZOutline;                                        // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAkComponent*                           Ak;                                                // 0x0390(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0398(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnCompleteInteraction;                             // 0x03A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BndEvt__BP_EMPTrap_TEST_SBZInteractable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature(class USBZBaseInteractableComponent* Interactable, class USBZInteractorComponent* Interactor, bool bIsLocallyControlledInteractor);
	void EnableVisibility();
	void ExecuteUbergraph_BP_EMPTrap_TEST(int32 EntryPoint);
	void GetState(int32* State_0);
	void OnStateChanged(int32 OldState, int32 NewState, bool bDoCosmetics);
	void ReceiveBeginPlay();
	void SetOffEmp();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_EMPTrap_TEST_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_EMPTrap_TEST_C")
	}
	static class ABP_EMPTrap_TEST_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EMPTrap_TEST_C>();
	}
};

SDK_NAMESPACE_END
