#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FOR_DeskTag_01_IanWagner

#include "Basic.hpp"

#include "BP_Tintable_Fixture_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_FOR_DeskTag_01_IanWagner.BP_FOR_DeskTag_01_IanWagner_C
// 0x0000 (0x0368 - 0x0368)
class ABP_FOR_DeskTag_01_IanWagner_C final : public ABP_Tintable_Fixture_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FOR_DeskTag_01_IanWagner_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FOR_DeskTag_01_IanWagner_C")
	}
	static class ABP_FOR_DeskTag_01_IanWagner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FOR_DeskTag_01_IanWagner_C>();
	}
};

SDK_NAMESPACE_END
