#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HoldOut_EnemyKilled

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_HoldOut_DroneReactionBase_classes.hpp"
#include "AkAudio_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_HoldOut_EnemyKilled.BP_HoldOut_EnemyKilled_C
// 0x0018 (0x0378 - 0x0360)
class ABP_HoldOut_EnemyKilled_C final : public ABP_HoldOut_DroneReactionBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_HoldOut_EnemyKilled_C;           // 0x0360(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      Niagara;                                           // 0x0368(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAkComponent*                           Ak;                                                // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_HoldOut_EnemyKilled(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_HoldOut_EnemyKilled_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_HoldOut_EnemyKilled_C")
	}
	static class ABP_HoldOut_EnemyKilled_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_HoldOut_EnemyKilled_C>();
	}
};

SDK_NAMESPACE_END
