#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HoldOut_WaitingForLoot

#include "Basic.hpp"

#include "BP_HoldOut_WaitingForLoot_classes.hpp"
#include "BP_HoldOut_WaitingForLoot_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_HoldOut_WaitingForLoot.BP_HoldOut_WaitingForLoot_C.ExecuteUbergraph_BP_HoldOut_WaitingForLoot
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HoldOut_WaitingForLoot_C::ExecuteUbergraph_BP_HoldOut_WaitingForLoot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HoldOut_WaitingForLoot_C", "ExecuteUbergraph_BP_HoldOut_WaitingForLoot");

	Params::BP_HoldOut_WaitingForLoot_C_ExecuteUbergraph_BP_HoldOut_WaitingForLoot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HoldOut_WaitingForLoot.BP_HoldOut_WaitingForLoot_C.OnLifeSpanChangedDueToInvalidation
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   NewLifeSpan                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HoldOut_WaitingForLoot_C::OnLifeSpanChangedDueToInvalidation(float NewLifeSpan)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HoldOut_WaitingForLoot_C", "OnLifeSpanChangedDueToInvalidation");

	Params::BP_HoldOut_WaitingForLoot_C_OnLifeSpanChangedDueToInvalidation Parms{};

	Parms.NewLifeSpan = NewLifeSpan;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HoldOut_WaitingForLoot.BP_HoldOut_WaitingForLoot_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_HoldOut_WaitingForLoot_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HoldOut_WaitingForLoot_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HoldOut_WaitingForLoot.BP_HoldOut_WaitingForLoot_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_HoldOut_WaitingForLoot_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HoldOut_WaitingForLoot_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HoldOut_WaitingForLoot.BP_HoldOut_WaitingForLoot_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_HoldOut_WaitingForLoot_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HoldOut_WaitingForLoot_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HoldOut_WaitingForLoot.BP_HoldOut_WaitingForLoot_C.Timeline_1__FinishedFunc
// (BlueprintEvent)

void ABP_HoldOut_WaitingForLoot_C::Timeline_1__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HoldOut_WaitingForLoot_C", "Timeline_1__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HoldOut_WaitingForLoot.BP_HoldOut_WaitingForLoot_C.Timeline_1__UpdateFunc
// (BlueprintEvent)

void ABP_HoldOut_WaitingForLoot_C::Timeline_1__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HoldOut_WaitingForLoot_C", "Timeline_1__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
