#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HoldOut_AreaCompleted

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_HoldOut_AreaCompleted.BP_HoldOut_AreaCompleted_C.ExecuteUbergraph_BP_HoldOut_AreaCompleted
// 0x0004 (0x0004 - 0x0000)
struct BP_HoldOut_AreaCompleted_C_ExecuteUbergraph_BP_HoldOut_AreaCompleted final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
