#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HoldOut_Area_Base

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_HoldOut_Area_Base.BP_HoldOut_Area_Base_C
// 0x0038 (0x0540 - 0x0508)
class ABP_HoldOut_Area_Base_C : public ASBZHoldOutArea
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0508(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TMulticastInlineDelegate<void(const struct FGameplayTag& Tag, bool bIsTagActive)> OnTagEvent;    // 0x0510(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<class UClass*>                         ConsumableClasses;                                 // 0x0520(0x0010)(Edit, BlueprintVisible)
	TArray<struct FTransform>                     ConsumableTransforms;                              // 0x0530(0x0010)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_BP_HoldOut_Area_Base(int32 EntryPoint);
	void OnAreaCompleted_Event_0(bool bIsSuccessful, class ASBZHoldOutArea* HoldOutArea);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_HoldOut_Area_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_HoldOut_Area_Base_C")
	}
	static class ABP_HoldOut_Area_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_HoldOut_Area_Base_C>();
	}
};

SDK_NAMESPACE_END
