#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Julius_Dongle

#include "Basic.hpp"

#include "BP_Charm_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Julius_Dongle.BP_Julius_Dongle_C
// 0x0000 (0x0350 - 0x0350)
class ABP_Julius_Dongle_C final : public ABP_Charm_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Julius_Dongle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Julius_Dongle_C")
	}
	static class ABP_Julius_Dongle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Julius_Dongle_C>();
	}
};

SDK_NAMESPACE_END
