#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LootableCarPart_doorBL

#include "Basic.hpp"

#include "BP_LootableCarPart_doorBL_classes.hpp"
#include "BP_LootableCarPart_doorBL_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_LootableCarPart_doorBL.BP_LootableCarPart_doorBL_C.ExecuteUbergraph_BP_LootableCarPart_doorBL
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LootableCarPart_doorBL_C::ExecuteUbergraph_BP_LootableCarPart_doorBL(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LootableCarPart_doorBL_C", "ExecuteUbergraph_BP_LootableCarPart_doorBL");

	Params::BP_LootableCarPart_doorBL_C_ExecuteUbergraph_BP_LootableCarPart_doorBL Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LootableCarPart_doorBL.BP_LootableCarPart_doorBL_C.OnStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   OldState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bDoCosmetics                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LootableCarPart_doorBL_C::OnStateChanged(int32 OldState, int32 NewState, bool bDoCosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LootableCarPart_doorBL_C", "OnStateChanged");

	Params::BP_LootableCarPart_doorBL_C_OnStateChanged Parms{};

	Parms.OldState = OldState;
	Parms.NewState = NewState;
	Parms.bDoCosmetics = bDoCosmetics;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
