#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LGT_FloodLight_01_1

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Master_Light_Fixture_classes.hpp"
#include "Starbreeze_structs.hpp"
#include "AkAudio_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LGT_FloodLight_01.BP_LGT_FloodLight_01_C
// 0x0020 (0x0460 - 0x0440)
class BP_LGT_FloodLight_01_1::ABP_LGT_FloodLight_01_C final : public ABP_Master_Light_Fixture_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0440(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USBZCosmeticDestructionComponent*       SBZCosmeticDestruction;                            // 0x0448(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight;                                         // 0x0450(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_LGT_FloodLight_01_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature(ESBZCosmeticDestructionType Type, const struct FSBZCosmeticDestructionContext& HitContext);
	void ExecuteUbergraph_BP_LGT_FloodLight_01(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_LGT_FloodLight_01.BP_LGT_FloodLight_01_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LGT_FloodLight_01_C")
	}
	static class BP_LGT_FloodLight_01_1::ABP_LGT_FloodLight_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_LGT_FloodLight_01_1::ABP_LGT_FloodLight_01_C>();
	}
};

SDK_NAMESPACE_END
