#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MoneyBagDyed

#include "Basic.hpp"

#include "BP_MoneyBagDyed_classes.hpp"
#include "BP_MoneyBagDyed_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_MoneyBagDyed.BP_MoneyBagDyed_C.ExecuteUbergraph_BP_MoneyBagDyed
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MoneyBagDyed_C::ExecuteUbergraph_BP_MoneyBagDyed(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MoneyBagDyed_C", "ExecuteUbergraph_BP_MoneyBagDyed");

	Params::BP_MoneyBagDyed_C_ExecuteUbergraph_BP_MoneyBagDyed Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MoneyBagDyed.BP_MoneyBagDyed_C.OnActorHit_Event
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SelfActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_MoneyBagDyed_C::OnActorHit_Event(class AActor* SelfActor, class AActor* OtherActor, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MoneyBagDyed_C", "OnActorHit_Event");

	Params::BP_MoneyBagDyed_C_OnActorHit_Event Parms{};

	Parms.SelfActor = SelfActor;
	Parms.OtherActor = OtherActor;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MoneyBagDyed.BP_MoneyBagDyed_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_MoneyBagDyed_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MoneyBagDyed_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
