#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlaceableSensorTool

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"
#include "AkAudio_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PlaceableSensorTool.BP_PlaceableSensorTool_C
// 0x0010 (0x06D0 - 0x06C0)
class ABP_PlaceableSensorTool_C final : public ASBZPlaceableSensorTool
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x06C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          Interactable_Collision;                            // 0x06C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_PlaceableSensorTool(int32 EntryPoint);
	void OnActivated();
	void OnSensorAmmoDepleted_Event_0();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PlaceableSensorTool_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PlaceableSensorTool_C")
	}
	static class ABP_PlaceableSensorTool_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PlaceableSensorTool_C>();
	}
};

SDK_NAMESPACE_END
