#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerGasRocketProjectile

#include "Basic.hpp"

#include "BP_PlayerGasRocketProjectile_classes.hpp"
#include "BP_PlayerGasRocketProjectile_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_PlayerGasRocketProjectile.BP_PlayerGasRocketProjectile_C.BP_OnDetonationCosmetics
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class UNiagaraComponent*                DetonationEffectComponent                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   ExplosionLocation                                      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   ExplosionImpactNormal                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerGasRocketProjectile_C::BP_OnDetonationCosmetics(class UNiagaraComponent* DetonationEffectComponent, const struct FVector& ExplosionLocation, const struct FVector& ExplosionImpactNormal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerGasRocketProjectile_C", "BP_OnDetonationCosmetics");

	Params::BP_PlayerGasRocketProjectile_C_BP_OnDetonationCosmetics Parms{};

	Parms.DetonationEffectComponent = DetonationEffectComponent;
	Parms.ExplosionLocation = std::move(ExplosionLocation);
	Parms.ExplosionImpactNormal = std::move(ExplosionImpactNormal);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerGasRocketProjectile.BP_PlayerGasRocketProjectile_C.ExecuteUbergraph_BP_PlayerGasRocketProjectile
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerGasRocketProjectile_C::ExecuteUbergraph_BP_PlayerGasRocketProjectile(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerGasRocketProjectile_C", "ExecuteUbergraph_BP_PlayerGasRocketProjectile");

	Params::BP_PlayerGasRocketProjectile_C_ExecuteUbergraph_BP_PlayerGasRocketProjectile Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerGasRocketProjectile.BP_PlayerGasRocketProjectile_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_PlayerGasRocketProjectile_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerGasRocketProjectile_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
