#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ProtectPoint

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ProtectPoint.BP_ProtectPoint_C
// 0x0000 (0x0388 - 0x0388)
class ABP_ProtectPoint_C : public ASBZAIProtectPoint
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ProtectPoint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ProtectPoint_C")
	}
	static class ABP_ProtectPoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ProtectPoint_C>();
	}
};

SDK_NAMESPACE_END
