#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ScreenDamageFeedback_OVK_Saw

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ScreenDamageFeedback_OVK_Saw.BP_ScreenDamageFeedback_OVK_Saw_C
// 0x0000 (0x0328 - 0x0328)
class UBP_ScreenDamageFeedback_OVK_Saw_C final : public USBZLocalPlayerFeedback
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ScreenDamageFeedback_OVK_Saw_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ScreenDamageFeedback_OVK_Saw_C")
	}
	static class UBP_ScreenDamageFeedback_OVK_Saw_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ScreenDamageFeedback_OVK_Saw_C>();
	}
};

SDK_NAMESPACE_END
