#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StaticCaptain_Sedan_02

#include "Basic.hpp"

#include "BP_StaticVehicle_Sedan_Civilian_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_StaticCaptain_Sedan_02.BP_StaticCaptain_Sedan_02_C
// 0x0000 (0x03D8 - 0x03D8)
class ABP_StaticCaptain_Sedan_02_C final : public ABP_StaticVehicle_Sedan_Civilian_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_StaticCaptain_Sedan_02_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_StaticCaptain_Sedan_02_C")
	}
	static class ABP_StaticCaptain_Sedan_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_StaticCaptain_Sedan_02_C>();
	}
};

SDK_NAMESPACE_END
