#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SafetyBox

#include "Basic.hpp"

#include "BP_SafetyBox_classes.hpp"
#include "BP_SafetyBox_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_SafetyBox.BP_SafetyBox_C.BndEvt__BP_SafetyBox_SBZPropDamage_K2Node_ComponentBoundEvent_0_SBZPropDamageHitsSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UActorComponent*                  PoolComponent                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   Hits                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bDoCosmetics                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FSBZPropDamageContext&     DamageContext                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void ABP_SafetyBox_C::BndEvt__BP_SafetyBox_SBZPropDamage_K2Node_ComponentBoundEvent_0_SBZPropDamageHitsSignature__DelegateSignature(class UActorComponent* PoolComponent, int32 Hits, bool bDoCosmetics, const struct FSBZPropDamageContext& DamageContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SafetyBox_C", "BndEvt__BP_SafetyBox_SBZPropDamage_K2Node_ComponentBoundEvent_0_SBZPropDamageHitsSignature__DelegateSignature");

	Params::BP_SafetyBox_C_BndEvt__BP_SafetyBox_SBZPropDamage_K2Node_ComponentBoundEvent_0_SBZPropDamageHitsSignature__DelegateSignature Parms{};

	Parms.PoolComponent = PoolComponent;
	Parms.Hits = Hits;
	Parms.bDoCosmetics = bDoCosmetics;
	Parms.DamageContext = std::move(DamageContext);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SafetyBox.BP_SafetyBox_C.BP_OnMiniGameSuccess
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bDoCosmetics                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SafetyBox_C::BP_OnMiniGameSuccess(bool bDoCosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SafetyBox_C", "BP_OnMiniGameSuccess");

	Params::BP_SafetyBox_C_BP_OnMiniGameSuccess Parms{};

	Parms.bDoCosmetics = bDoCosmetics;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SafetyBox.BP_SafetyBox_C.ExecuteUbergraph_BP_SafetyBox
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SafetyBox_C::ExecuteUbergraph_BP_SafetyBox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SafetyBox_C", "ExecuteUbergraph_BP_SafetyBox");

	Params::BP_SafetyBox_C_ExecuteUbergraph_BP_SafetyBox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SafetyBox.BP_SafetyBox_C.OnActorSpawned
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SpawnedActor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class USceneComponent*                  AttachParent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_SafetyBox_C::OnActorSpawned(class AActor* SpawnedActor, class USceneComponent* AttachParent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SafetyBox_C", "OnActorSpawned");

	Params::BP_SafetyBox_C_OnActorSpawned Parms{};

	Parms.SpawnedActor = SpawnedActor;
	Parms.AttachParent = AttachParent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SafetyBox.BP_SafetyBox_C.PopulateSpawnInformationMap
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TMap<class USceneComponent*, struct FTransform>*InOutSpawnDataMap                                      (Parm, OutParm, ContainsInstancedReference)

void ABP_SafetyBox_C::PopulateSpawnInformationMap(TMap<class USceneComponent*, struct FTransform>* InOutSpawnDataMap)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SafetyBox_C", "PopulateSpawnInformationMap");

	Params::BP_SafetyBox_C_PopulateSpawnInformationMap Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (InOutSpawnDataMap != nullptr)
		*InOutSpawnDataMap = std::move(Parms.InOutSpawnDataMap);
}


// Function BP_SafetyBox.BP_SafetyBox_C.Relocate
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_SafetyBox_C::Relocate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SafetyBox_C", "Relocate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SafetyBox.BP_SafetyBox_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_SafetyBox_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SafetyBox_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
