#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SniperController

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SniperController.BP_SniperController_C
// 0x0008 (0x0760 - 0x0758)
class ABP_SniperController_C final : public ASBZAIController
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0758(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_SniperController(int32 EntryPoint);
	void ReceivePossess(class APawn* PossessedPawn);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SniperController_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SniperController_C")
	}
	static class ABP_SniperController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SniperController_C>();
	}
};

SDK_NAMESPACE_END
