#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPL_StreetVictorian_03_A

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPL_StreetVictorian_03_A.BPL_StreetVictorian_03_A_C
// 0x0030 (0x0358 - 0x0328)
class ABPL_StreetVictorian_03_A_C final : public AActor
{
public:
	class UStaticMeshComponent*                   Sphere;                                            // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   PointLight_1;                                      // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   PointLight;                                        // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      FX_Moths;                                          // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LGT_StreetVictorian_03;                            // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPL_StreetVictorian_03_A_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPL_StreetVictorian_03_A_C")
	}
	static class ABPL_StreetVictorian_03_A_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPL_StreetVictorian_03_A_C>();
	}
};

SDK_NAMESPACE_END
