#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BUST_BPL_ConstructionTripod1

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"
#include "Enum_LampStages_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BUST_BPL_ConstructionTripod1.BUST_BPL_ConstructionTripod1_C
// 0x0058 (0x03C8 - 0x0370)
class ABUST_BPL_ConstructionTripod1_C final : public ASBZReplicatedIntStateActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPointLightComponent*                   PointLight;                                        // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   PointLight_1;                                      // 0x0380(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight;                                         // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LGT_ConstructionTripod_01_Spotlight_1;             // 0x0390(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LGT_ConstructionTripod_01_Bracket_1;               // 0x0398(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LGT_ConstructionTripod_01_Spotlight;               // 0x03A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LGT_ConstructionTripod_01_Bracket;                 // 0x03A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LGT_DeskLamp_0_4;                                  // 0x03B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	Enum_LampStages                               States;                                            // 0x03C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BUST_BPL_ConstructionTripod1(int32 EntryPoint);
	void OnStateChanged(int32 OldState, int32 NewState, bool bDoCosmetics);
	void SetStateFunction(Enum_LampStages States_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BUST_BPL_ConstructionTripod1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BUST_BPL_ConstructionTripod1_C")
	}
	static class ABUST_BPL_ConstructionTripod1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABUST_BPL_ConstructionTripod1_C>();
	}
};

SDK_NAMESPACE_END
