#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CH_Cloaker

#include "Basic.hpp"

#include "CH_BaseCop_classes.hpp"
#include "Engine_structs.hpp"
#include "Starbreeze_structs.hpp"
#include "AkAudio_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CH_Cloaker.CH_Cloaker_C
// 0x0010 (0x21D0 - 0x21C0)
class ACH_Cloaker_C final : public ACH_BaseCop_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x21C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      Niagara;                                           // 0x21C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void BP_OnHeistStateChanged(EPD3HeistState OldState, EPD3HeistState NewState);
	void BP_OnKill();
	void BP_OnTagReactionPlayed();
	void ExecuteUbergraph_CH_Cloaker(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CH_Cloaker_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CH_Cloaker_C")
	}
	static class ACH_Cloaker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACH_Cloaker_C>();
	}
};

SDK_NAMESPACE_END
