#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CH_SecurityGuard_LongerOutline

#include "Basic.hpp"

#include "CH_SecurityGuard_LongerOutline_classes.hpp"
#include "CH_SecurityGuard_LongerOutline_parameters.hpp"


SDK_NAMESPACE_START

// Function CH_SecurityGuard_LongerOutline.CH_SecurityGuard_LongerOutline_C.BP_OnHeistStateChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// EPD3HeistState                          OldState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EPD3HeistState                          NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACH_SecurityGuard_LongerOutline_C::BP_OnHeistStateChanged(EPD3HeistState OldState, EPD3HeistState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_SecurityGuard_LongerOutline_C", "BP_OnHeistStateChanged");

	Params::CH_SecurityGuard_LongerOutline_C_BP_OnHeistStateChanged Parms{};

	Parms.OldState = OldState;
	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CH_SecurityGuard_LongerOutline.CH_SecurityGuard_LongerOutline_C.BP_OnKill
// (Event, Public, BlueprintEvent)

void ACH_SecurityGuard_LongerOutline_C::BP_OnKill()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_SecurityGuard_LongerOutline_C", "BP_OnKill");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CH_SecurityGuard_LongerOutline.CH_SecurityGuard_LongerOutline_C.ExecuteUbergraph_CH_SecurityGuard_LongerOutline
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACH_SecurityGuard_LongerOutline_C::ExecuteUbergraph_CH_SecurityGuard_LongerOutline(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_SecurityGuard_LongerOutline_C", "ExecuteUbergraph_CH_SecurityGuard_LongerOutline");

	Params::CH_SecurityGuard_LongerOutline_C_ExecuteUbergraph_CH_SecurityGuard_LongerOutline Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CH_SecurityGuard_LongerOutline.CH_SecurityGuard_LongerOutline_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ACH_SecurityGuard_LongerOutline_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_SecurityGuard_LongerOutline_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
