#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: L_DataCenter_DynamicLighting

#include "Basic.hpp"

#include "L_DataCenter_DynamicLighting_classes.hpp"
#include "L_DataCenter_DynamicLighting_parameters.hpp"


SDK_NAMESPACE_START

// Function L_DataCenter_DynamicLighting.L_DataCenter_DynamicLighting_C.ExecuteUbergraph_L_DataCenter_DynamicLighting
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AL_DataCenter_DynamicLighting_C::ExecuteUbergraph_L_DataCenter_DynamicLighting(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("L_DataCenter_DynamicLighting_C", "ExecuteUbergraph_L_DataCenter_DynamicLighting");

	Params::L_DataCenter_DynamicLighting_C_ExecuteUbergraph_L_DataCenter_DynamicLighting Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function L_DataCenter_DynamicLighting.L_DataCenter_DynamicLighting_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AL_DataCenter_DynamicLighting_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("L_DataCenter_DynamicLighting_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function L_DataCenter_DynamicLighting.L_DataCenter_DynamicLighting_C.RoomACleared
// (BlueprintCallable, BlueprintEvent)

void AL_DataCenter_DynamicLighting_C::RoomACleared()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("L_DataCenter_DynamicLighting_C", "RoomACleared");

	UObject::ProcessEvent(Func, nullptr);
}


// Function L_DataCenter_DynamicLighting.L_DataCenter_DynamicLighting_C.RoomBCleared
// (BlueprintCallable, BlueprintEvent)

void AL_DataCenter_DynamicLighting_C::RoomBCleared()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("L_DataCenter_DynamicLighting_C", "RoomBCleared");

	UObject::ProcessEvent(Func, nullptr);
}


// Function L_DataCenter_DynamicLighting.L_DataCenter_DynamicLighting_C.RoomCCleared
// (BlueprintCallable, BlueprintEvent)

void AL_DataCenter_DynamicLighting_C::RoomCCleared()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("L_DataCenter_DynamicLighting_C", "RoomCCleared");

	UObject::ProcessEvent(Func, nullptr);
}


// Function L_DataCenter_DynamicLighting.L_DataCenter_DynamicLighting_C.RoomDCleared
// (BlueprintCallable, BlueprintEvent)

void AL_DataCenter_DynamicLighting_C::RoomDCleared()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("L_DataCenter_DynamicLighting_C", "RoomDCleared");

	UObject::ProcessEvent(Func, nullptr);
}


// Function L_DataCenter_DynamicLighting.L_DataCenter_DynamicLighting_C.RoomECleared
// (BlueprintCallable, BlueprintEvent)

void AL_DataCenter_DynamicLighting_C::RoomECleared()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("L_DataCenter_DynamicLighting_C", "RoomECleared");

	UObject::ProcessEvent(Func, nullptr);
}


// Function L_DataCenter_DynamicLighting.L_DataCenter_DynamicLighting_C.WallExplodedTrigger
// (BlueprintCallable, BlueprintEvent)

void AL_DataCenter_DynamicLighting_C::WallExplodedTrigger()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("L_DataCenter_DynamicLighting_C", "WallExplodedTrigger");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
