#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NW_NC_Sparks

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass NW_NC_Sparks.NW_NC_Sparks_C
// 0x0010 (0x0338 - 0x0328)
class ANW_NC_Sparks_C final : public AActor
{
public:
	class USBZNiagaraWwiseComponentNonOpt*        SBZNiagaraWwiseComponentNonOpt;                    // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NW_NC_Sparks_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NW_NC_Sparks_C")
	}
	static class ANW_NC_Sparks_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANW_NC_Sparks_C>();
	}
};

SDK_NAMESPACE_END
