#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OptimusCore

#include "Basic.hpp"

#include "ComputeFramework_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "RigVM_structs.hpp"
#include "ControlRig_structs.hpp"


SDK_NAMESPACE_START

// Enum OptimusCore.EOptimusPinMutability
// NumValues: 0x0004
enum class EOptimusPinMutability : uint8
{
	Undefined                                = 0,
	Immutable                                = 1,
	Mutable                                  = 2,
	EOptimusPinMutability_MAX                = 3,
};

// Enum OptimusCore.EOptimusConstantType
// NumValues: 0x0003
enum class EOptimusConstantType : uint32
{
	Input                                    = 0,
	Output                                   = 1,
	EOptimusConstantType_MAX                 = 2,
};

// Enum OptimusCore.EOptimusDeformerExecutionPhase
// NumValues: 0x0004
enum class EOptimusDeformerExecutionPhase : uint8
{
	AfterDefaultDeformer                     = 0,
	OverrideDefaultDeformer                  = 1,
	BeforeDefaultDeformer                    = 2,
	EOptimusDeformerExecutionPhase_MAX       = 3,
};

// Enum OptimusCore.EOptimusDiagnosticLevel
// NumValues: 0x0005
enum class EOptimusDiagnosticLevel : uint8
{
	None                                     = 0,
	Info                                     = 1,
	Warning                                  = 2,
	Error                                    = 3,
	EOptimusDiagnosticLevel_MAX              = 4,
};

// Enum OptimusCore.EOptimusValueUsage
// NumValues: 0x0004
enum class EOptimusValueUsage : uint8
{
	None                                     = 0,
	CPU                                      = 1,
	GPU                                      = 2,
	EOptimusValueUsage_MAX                   = 3,
};

// Enum OptimusCore.EOptimusValueType
// NumValues: 0x0004
enum class EOptimusValueType : uint8
{
	Invalid                                  = 0,
	Constant                                 = 1,
	Variable                                 = 2,
	EOptimusValueType_MAX                    = 3,
};

// Enum OptimusCore.EOptimusBufferWriteType
// NumValues: 0x0006
enum class EOptimusBufferWriteType : uint8
{
	Write                                    = 0,
	WriteAtomicAdd                           = 1,
	WriteAtomicMin                           = 2,
	WriteAtomicMax                           = 3,
	Count                                    = 4,
	EOptimusBufferWriteType_MAX              = 5,
};

// Enum OptimusCore.EOptimusSkinnedMeshExecDomain
// NumValues: 0x0004
enum class EOptimusSkinnedMeshExecDomain : uint8
{
	None                                     = 0,
	Vertex                                   = 1,
	Triangle                                 = 2,
	EOptimusSkinnedMeshExecDomain_MAX        = 3,
};

// Enum OptimusCore.EOptimusTerminalType
// NumValues: 0x0004
enum class EOptimusTerminalType : uint32
{
	Unknown                                  = 0,
	Entry                                    = 1,
	Return                                   = 2,
	EOptimusTerminalType_MAX                 = 3,
};

// Enum OptimusCore.EOptimusDataDomainType
// NumValues: 0x0003
enum class EOptimusDataDomainType : uint32
{
	Dimensional                              = 0,
	Expression                               = 1,
	EOptimusDataDomainType_MAX               = 2,
};

// Enum OptimusCore.EOptimusDataTypeUsageFlags
// NumValues: 0x0009
enum class EOptimusDataTypeUsageFlags : uint8
{
	None                                     = 0,
	Resource                                 = 1,
	Variable                                 = 2,
	AnimAttributes                           = 4,
	DataInterfaceOutput                      = 8,
	PinType                                  = 16,
	PerBoneAnimAttribute                     = 32,
	Property                                 = 64,
	EOptimusDataTypeUsageFlags_MAX           = 65,
};

// Enum OptimusCore.EOptimusDataTypeFlags
// NumValues: 0x0004
enum class EOptimusDataTypeFlags : uint8
{
	None                                     = 0,
	IsStructType                             = 1,
	ShowElements                             = 2,
	EOptimusDataTypeFlags_MAX                = 3,
};

// Enum OptimusCore.EOptimusDeformerStatus
// NumValues: 0x0005
enum class EOptimusDeformerStatus : uint32
{
	Compiled                                 = 0,
	CompiledWithWarnings                     = 1,
	Modified                                 = 2,
	HasErrors                                = 3,
	EOptimusDeformerStatus_MAX               = 4,
};

// Enum OptimusCore.EOptimusExecutionDomainType
// NumValues: 0x0003
enum class EOptimusExecutionDomainType : uint32
{
	DomainName                               = 0,
	Expression                               = 1,
	EOptimusExecutionDomainType_MAX          = 2,
};

// Enum OptimusCore.EOptimusNodeGraphType
// NumValues: 0x0007
enum class EOptimusNodeGraphType : uint32
{
	Setup                                    = 0,
	Update                                   = 1,
	ExternalTrigger                          = 2,
	Function                                 = 3,
	SubGraph                                 = 4,
	Transient                                = 5,
	EOptimusNodeGraphType_MAX                = 6,
};

// Enum OptimusCore.EOptimusNodePinStorageType
// NumValues: 0x0003
enum class EOptimusNodePinStorageType : uint8
{
	Value                                    = 0,
	Resource                                 = 1,
	EOptimusNodePinStorageType_MAX           = 2,
};

// Enum OptimusCore.EOptimusNodePinDirection
// NumValues: 0x0004
enum class EOptimusNodePinDirection : uint8
{
	Unknown                                  = 0,
	Input                                    = 1,
	Output                                   = 2,
	EOptimusNodePinDirection_MAX             = 3,
};

// ScriptStruct OptimusCore.OptimusDataTypeRef
// 0x0040 (0x0040 - 0x0000)
struct FOptimusDataTypeRef
{
public:
	class FName                                   TypeName;                                          // 0x0000(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UObject>                 TypeObject;                                        // 0x0010(0x0030)(Edit, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.Optimus_ShaderBinding
// 0x0050 (0x0050 - 0x0000)
struct FOptimus_ShaderBinding
{
public:
	class FName                                   Name;                                              // 0x0000(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOptimusDataTypeRef                    DataType;                                          // 0x0010(0x0040)(Edit, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusValidatedName
// 0x000C (0x000C - 0x0000)
struct FOptimusValidatedName
{
public:
	class FName                                   Name;                                              // 0x0000(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusDataDomain
// 0x0040 (0x0040 - 0x0000)
struct FOptimusDataDomain
{
public:
	EOptimusDataDomainType                        Type;                                              // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FName>                           DimensionNames;                                    // 0x0008(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
	int32                                         Multiplier;                                        // 0x0018(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Expression;                                        // 0x0020(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FName>                           LevelNames;                                        // 0x0030(0x0010)(ZeroConstructor, Deprecated, NativeAccessSpecifierPrivate)
};

// ScriptStruct OptimusCore.OptimusParameterBinding
// 0x0098 (0x0098 - 0x0000)
struct FOptimusParameterBinding
{
public:
	struct FOptimusValidatedName                  Name;                                              // 0x0000(0x000C)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOptimusDataTypeRef                    DataType;                                          // 0x0010(0x0040)(Edit, NativeAccessSpecifierPublic)
	struct FOptimusDataDomain                     DataDomain;                                        // 0x0050(0x0040)(Edit, NativeAccessSpecifierPublic)
	bool                                          bSupportAtomicIfCompatibleDataType;                // 0x0090(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSupportRead;                                      // 0x0091(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_92[0x6];                                       // 0x0092(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusParameterBindingArray
// 0x0010 (0x0010 - 0x0000)
struct FOptimusParameterBindingArray
{
public:
	TArray<struct FOptimusParameterBinding>       InnerArray;                                        // 0x0000(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusConstantIdentifier
// 0x0024 (0x0024 - 0x0000)
struct FOptimusConstantIdentifier
{
public:
	class FName                                   NodePath;                                          // 0x0000(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   GroupName;                                         // 0x000C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ConstantName;                                      // 0x0018(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusConstantDefinition
// 0x0038 (0x0038 - 0x0000)
struct FOptimusConstantDefinition
{
public:
	struct FOptimusConstantIdentifier             ReferencedConstant;                                // 0x0000(0x0024)(NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Expression;                                        // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusConstant
// 0x0068 (0x0068 - 0x0000)
struct FOptimusConstant
{
public:
	struct FOptimusConstantIdentifier             Identifier;                                        // 0x0000(0x0024)(NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOptimusConstantDefinition             Definition;                                        // 0x0028(0x0038)(NativeAccessSpecifierPublic)
	int32                                         ComponentBindingIndex;                             // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOptimusConstantType                          Type;                                              // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusConstantIndex
// 0x000C (0x000C - 0x0000)
struct FOptimusConstantIndex
{
public:
	int32                                         KernelIndex;                                       // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOptimusConstantType                          Type;                                              // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ConstantIndex;                                     // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusKernelConstantContainer
// 0x0070 (0x0070 - 0x0000)
struct FOptimusKernelConstantContainer
{
public:
	TArray<struct FOptimusConstant>               InputConstants;                                    // 0x0000(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FOptimusConstant>               OutputConstants;                                   // 0x0010(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TMap<class FName, int32>                      GroupNameToBindingIndex;                           // 0x0020(0x0050)(NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusConstantContainer
// 0x0010 (0x0010 - 0x0000)
struct FOptimusConstantContainer
{
public:
	TArray<struct FOptimusKernelConstantContainer> KernelContainers;                                 // 0x0000(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
};

// ScriptStruct OptimusCore.OptimusShaderText
// 0x0020 (0x0020 - 0x0000)
struct FOptimusShaderText
{
public:
	class FString                                 Declarations;                                      // 0x0000(0x0010)(Edit, ZeroConstructor, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ShaderText;                                        // 0x0010(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusValueIdentifier
// 0x0010 (0x0010 - 0x0000)
struct FOptimusValueIdentifier
{
public:
	EOptimusValueType                             Type;                                              // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   Name;                                              // 0x0004(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusValueContainerStruct
// 0x0010 (0x0010 - 0x0000)
struct FOptimusValueContainerStruct
{
public:
	struct FInstancedPropertyBag                  Value;                                             // 0x0000(0x0010)(Edit, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusValueDescription
// 0x0078 (0x0078 - 0x0000)
struct FOptimusValueDescription
{
public:
	struct FOptimusDataTypeRef                    DataType;                                          // 0x0000(0x0040)(NativeAccessSpecifierPublic)
	EOptimusValueUsage                            ValueUsage;                                        // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOptimusValueContainerStruct           Value;                                             // 0x0048(0x0010)(NativeAccessSpecifierPublic)
	struct FShaderValueContainer                  ShaderValue;                                       // 0x0058(0x0020)(NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusDataInterfacePropertyOverrideInfo
// 0x0050 (0x0050 - 0x0000)
struct FOptimusDataInterfacePropertyOverrideInfo
{
public:
	TMap<class FName, struct FOptimusValueIdentifier> PinNameToValueIdMap;                           // 0x0000(0x0050)(NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_OptimusDeformer
// 0x0030 (0x0048 - 0x0018)
struct FRigVMTrait_OptimusDeformer : public FRigVMTrait
{
public:
	TSoftObjectPtr<class UOptimusDeformer>        DeformerGraph;                                     // 0x0018(0x0030)(Edit, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_OptimusDeformerSettings
// 0x0018 (0x0030 - 0x0018)
struct FRigVMTrait_OptimusDeformerSettings : public FRigVMTrait
{
public:
	EOptimusDeformerExecutionPhase                ExecutionPhase;                                    // 0x0018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ExecutionGroup;                                    // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          DeformChildComponents;                             // 0x0020(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   ExcludeChildComponentsWithTag;                     // 0x0024(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigUnit_AddOptimusDeformer
// 0x0010 (0x0200 - 0x01F0)
struct FRigUnit_AddOptimusDeformer : public FRigUnitMutable
{
public:
	struct FGuid                                  DeformerInstanceGuid;                              // 0x01F0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_OptimusVariableBase
// 0x0000 (0x0018 - 0x0018)
struct FRigVMTrait_OptimusVariableBase : public FRigVMTrait
{
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerIntVariable
// 0x0008 (0x0020 - 0x0018)
struct FRigVMTrait_SetDeformerIntVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	int32                                         Value;                                             // 0x0018(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerIntArrayVariable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerIntArrayVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	TArray<int32>                                 Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerInt2Variable
// 0x0008 (0x0020 - 0x0018)
struct FRigVMTrait_SetDeformerInt2Variable : public FRigVMTrait_OptimusVariableBase
{
public:
	struct FIntPoint                              Value;                                             // 0x0018(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerInt2ArrayVariable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerInt2ArrayVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	TArray<struct FIntPoint>                      Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerInt3Variable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerInt3Variable : public FRigVMTrait_OptimusVariableBase
{
public:
	struct FIntVector                             Value;                                             // 0x0018(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerInt3ArrayVariable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerInt3ArrayVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	TArray<struct FIntVector>                     Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerInt4Variable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerInt4Variable : public FRigVMTrait_OptimusVariableBase
{
public:
	struct FIntVector4                            Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerInt4ArrayVariable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerInt4ArrayVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	TArray<struct FIntVector4>                    Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerFloatVariable
// 0x0008 (0x0020 - 0x0018)
struct FRigVMTrait_SetDeformerFloatVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	double                                        Value;                                             // 0x0018(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerFloatArrayVariable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerFloatArrayVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	TArray<double>                                Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerVector2Variable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerVector2Variable : public FRigVMTrait_OptimusVariableBase
{
public:
	struct FVector2D                              Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerVector2ArrayVariable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerVector2ArrayVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	TArray<struct FVector2D>                      Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerVectorVariable
// 0x0018 (0x0030 - 0x0018)
struct FRigVMTrait_SetDeformerVectorVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	struct FVector                                Value;                                             // 0x0018(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerVectorArrayVariable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerVectorArrayVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	TArray<struct FVector>                        Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerVector4Variable
// 0x0028 (0x0040 - 0x0018)
struct FRigVMTrait_SetDeformerVector4Variable : public FRigVMTrait_OptimusVariableBase
{
public:
	uint8                                         Pad_18[0x8];                                       // 0x0018(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector4                               Value;                                             // 0x0020(0x0020)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerVector4ArrayVariable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerVector4ArrayVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	TArray<struct FVector4>                       Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerLinearColorVariable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerLinearColorVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	struct FLinearColor                           Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerLinearColorArrayVariable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerLinearColorArrayVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	TArray<struct FLinearColor>                   Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerQuatVariable
// 0x0028 (0x0040 - 0x0018)
struct FRigVMTrait_SetDeformerQuatVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	uint8                                         Pad_18[0x8];                                       // 0x0018(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FQuat                                  Value;                                             // 0x0020(0x0020)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerQuatArrayVariable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerQuatArrayVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	TArray<struct FQuat>                          Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerRotatorVariable
// 0x0018 (0x0030 - 0x0018)
struct FRigVMTrait_SetDeformerRotatorVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	struct FRotator                               Value;                                             // 0x0018(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerRotatorArrayVariable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerRotatorArrayVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	TArray<struct FRotator>                       Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerTransformVariable
// 0x0068 (0x0080 - 0x0018)
struct FRigVMTrait_SetDeformerTransformVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	uint8                                         Pad_18[0x8];                                       // 0x0018(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             Value;                                             // 0x0020(0x0060)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerTransformArrayVariable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerTransformArrayVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	TArray<struct FTransform>                     Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerNameVariable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerNameVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	class FName                                   Value;                                             // 0x0018(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerNameArrayVariable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerNameArrayVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	TArray<class FName>                           Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerBoolVariable
// 0x0008 (0x0020 - 0x0018)
struct FRigVMTrait_SetDeformerBoolVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	bool                                          Value;                                             // 0x0018(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.RigVMTrait_SetDeformerBoolArrayVariable
// 0x0010 (0x0028 - 0x0018)
struct FRigVMTrait_SetDeformerBoolArrayVariable : public FRigVMTrait_OptimusVariableBase
{
public:
	TArray<bool>                                  Value;                                             // 0x0018(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusAction
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x08) FOptimusAction
{
public:
	uint8                                         Pad_0[0x18];                                       // 0x0000(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusCompoundAction
// 0x0010 (0x0028 - 0x0018)
struct FOptimusCompoundAction : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x10];                                      // 0x0018(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusComponentBindingAction_AddBinding
// 0x0028 (0x0040 - 0x0018)
struct FOptimusComponentBindingAction_AddBinding : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x28];                                      // 0x0018(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusComponentBindingAction_RemoveBinding
// 0x0040 (0x0058 - 0x0018)
struct FOptimusComponentBindingAction_RemoveBinding : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x40];                                      // 0x0018(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusComponentBindingAction_RenameBinding
// 0x0018 (0x0030 - 0x0018)
struct FOptimusComponentBindingAction_RenameBinding : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x18];                                      // 0x0018(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusComponentBindingAction_SetComponentSource
// 0x0040 (0x0058 - 0x0018)
struct FOptimusComponentBindingAction_SetComponentSource : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x40];                                      // 0x0018(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeAction_RenameNode
// 0x0030 (0x0048 - 0x0018)
struct FOptimusNodeAction_RenameNode : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x30];                                      // 0x0018(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeAction_MoveNode
// 0x0030 (0x0048 - 0x0018)
struct FOptimusNodeAction_MoveNode : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x30];                                      // 0x0018(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeAction_SetPinValue
// 0x0030 (0x0048 - 0x0018)
struct FOptimusNodeAction_SetPinValue : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x30];                                      // 0x0018(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeAction_SetPinName
// 0x0028 (0x0040 - 0x0018)
struct FOptimusNodeAction_SetPinName : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x28];                                      // 0x0018(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeAction_SetPinType
// 0x0028 (0x0040 - 0x0018)
struct FOptimusNodeAction_SetPinType : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x28];                                      // 0x0018(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeAction_SetPinDataDomain
// 0x0090 (0x00A8 - 0x0018)
struct FOptimusNodeAction_SetPinDataDomain : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x90];                                      // 0x0018(0x0090)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeAction_AddRemovePin
// 0x00A8 (0x00C0 - 0x0018)
struct FOptimusNodeAction_AddRemovePin : public FOptimusAction
{
public:
	uint8                                         Pad_18[0xA8];                                      // 0x0018(0x00A8)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeAction_AddPin
// 0x0000 (0x00C0 - 0x00C0)
struct FOptimusNodeAction_AddPin : public FOptimusNodeAction_AddRemovePin
{
};

// ScriptStruct OptimusCore.OptimusNodeAction_AddGroupingPin
// 0x0000 (0x00C0 - 0x00C0)
struct FOptimusNodeAction_AddGroupingPin : public FOptimusNodeAction_AddRemovePin
{
};

// ScriptStruct OptimusCore.OptimusNodeAction_RemovePin
// 0x0000 (0x00C0 - 0x00C0)
struct FOptimusNodeAction_RemovePin : public FOptimusNodeAction_AddRemovePin
{
};

// ScriptStruct OptimusCore.OptimusNodeAction_MovePin
// 0x0030 (0x0048 - 0x0018)
struct FOptimusNodeAction_MovePin : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x30];                                      // 0x0018(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeGraphAction_AddGraph
// 0x0078 (0x0090 - 0x0018)
struct alignas(0x10) FOptimusNodeGraphAction_AddGraph final : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x78];                                      // 0x0018(0x0078)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeGraphAction_RemoveGraph
// 0x0048 (0x0060 - 0x0018)
struct FOptimusNodeGraphAction_RemoveGraph : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x48];                                      // 0x0018(0x0048)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeGraphAction_RenameGraph
// 0x0038 (0x0050 - 0x0018)
struct FOptimusNodeGraphAction_RenameGraph : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x38];                                      // 0x0018(0x0038)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeGraphAction_AddNode
// 0x0088 (0x00A0 - 0x0018)
struct alignas(0x10) FOptimusNodeGraphAction_AddNode final : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x88];                                      // 0x0018(0x0088)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeGraphAction_DuplicateNode
// 0x00A8 (0x00C0 - 0x0018)
struct alignas(0x10) FOptimusNodeGraphAction_DuplicateNode final : public FOptimusAction
{
public:
	uint8                                         Pad_18[0xA8];                                      // 0x0018(0x00A8)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeGraphAction_RemoveNode
// 0x0050 (0x0068 - 0x0018)
struct FOptimusNodeGraphAction_RemoveNode : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x50];                                      // 0x0018(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeGraphAction_AddRemoveNodePair
// 0x0020 (0x0038 - 0x0018)
struct FOptimusNodeGraphAction_AddRemoveNodePair : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x20];                                      // 0x0018(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeGraphAction_AddNodePair
// 0x0020 (0x0058 - 0x0038)
struct FOptimusNodeGraphAction_AddNodePair : public FOptimusNodeGraphAction_AddRemoveNodePair
{
public:
	uint8                                         Pad_38[0x20];                                      // 0x0038(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeGraphAction_RemoveNodePair
// 0x0000 (0x0038 - 0x0038)
struct FOptimusNodeGraphAction_RemoveNodePair : public FOptimusNodeGraphAction_AddRemoveNodePair
{
};

// ScriptStruct OptimusCore.OptimusNodeGraphAction_AddRemoveLink
// 0x0028 (0x0040 - 0x0018)
struct FOptimusNodeGraphAction_AddRemoveLink : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x28];                                      // 0x0018(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeGraphAction_AddLink
// 0x0000 (0x0040 - 0x0040)
struct FOptimusNodeGraphAction_AddLink : public FOptimusNodeGraphAction_AddRemoveLink
{
};

// ScriptStruct OptimusCore.OptimusNodeGraphAction_RemoveLink
// 0x0000 (0x0040 - 0x0040)
struct FOptimusNodeGraphAction_RemoveLink : public FOptimusNodeGraphAction_AddRemoveLink
{
};

// ScriptStruct OptimusCore.OptimusNodeGraphAction_ConnectAdderPin
// 0x0068 (0x00A8 - 0x0040)
struct FOptimusNodeGraphAction_ConnectAdderPin : public FOptimusNodeGraphAction_AddRemoveLink
{
public:
	uint8                                         Pad_40[0x68];                                      // 0x0040(0x0068)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeGraphAction_PackageKernelFunction
// 0x00A8 (0x00C0 - 0x0018)
struct FOptimusNodeGraphAction_PackageKernelFunction : public FOptimusAction
{
public:
	uint8                                         Pad_18[0xA8];                                      // 0x0018(0x00A8)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusNodeGraphAction_UnpackageKernelFunction
// 0x0050 (0x0068 - 0x0018)
struct FOptimusNodeGraphAction_UnpackageKernelFunction : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x50];                                      // 0x0018(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusResourceAction_AddResource
// 0x0090 (0x00A8 - 0x0018)
struct FOptimusResourceAction_AddResource : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x90];                                      // 0x0018(0x0090)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusResourceAction_RemoveResource
// 0x0068 (0x0080 - 0x0018)
struct FOptimusResourceAction_RemoveResource : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x68];                                      // 0x0018(0x0068)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusResourceAction_RenameResource
// 0x0018 (0x0030 - 0x0018)
struct FOptimusResourceAction_RenameResource : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x18];                                      // 0x0018(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusResourceAction_SetDataType
// 0x0090 (0x00A8 - 0x0018)
struct FOptimusResourceAction_SetDataType : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x90];                                      // 0x0018(0x0090)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusResourceAction_SetDataDomain
// 0x0090 (0x00A8 - 0x0018)
struct FOptimusResourceAction_SetDataDomain : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x90];                                      // 0x0018(0x0090)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusVariableAction_AddVariable
// 0x0050 (0x0068 - 0x0018)
struct FOptimusVariableAction_AddVariable : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x50];                                      // 0x0018(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusVariableAction_RemoveVariable
// 0x0078 (0x0090 - 0x0018)
struct FOptimusVariableAction_RemoveVariable : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x78];                                      // 0x0018(0x0078)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusVariableAction_RenameVariable
// 0x0018 (0x0030 - 0x0018)
struct FOptimusVariableAction_RenameVariable : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x18];                                      // 0x0018(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusVariableAction_SetDataType
// 0x0090 (0x00A8 - 0x0018)
struct FOptimusVariableAction_SetDataType : public FOptimusAction
{
public:
	uint8                                         Pad_18[0x90];                                      // 0x0018(0x0090)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusAnimAttributeBufferDescription
// 0x0080 (0x0080 - 0x0000)
struct FOptimusAnimAttributeBufferDescription
{
public:
	class FString                                 Name;                                              // 0x0000(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FOptimusDataTypeRef                    DataType;                                          // 0x0010(0x0040)(Edit, NativeAccessSpecifierPublic)
	struct FOptimusValueContainerStruct           DefaultValueStruct;                                // 0x0050(0x0010)(Edit, NativeAccessSpecifierPublic)
	class FString                                 HlslId;                                            // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   PinName;                                           // 0x0070(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7C[0x4];                                       // 0x007C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusAnimAttributeBufferArray
// 0x0010 (0x0010 - 0x0000)
struct FOptimusAnimAttributeBufferArray
{
public:
	TArray<struct FOptimusAnimAttributeBufferDescription> InnerArray;                                // 0x0000(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusAnimAttributeDescription
// 0x0098 (0x0098 - 0x0000)
struct FOptimusAnimAttributeDescription
{
public:
	class FString                                 Name;                                              // 0x0000(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   BoneName;                                          // 0x0010(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOptimusDataTypeRef                    DataType;                                          // 0x0020(0x0040)(Edit, NativeAccessSpecifierPublic)
	struct FOptimusValueContainerStruct           DefaultValueStruct;                                // 0x0060(0x0010)(Edit, NativeAccessSpecifierPublic)
	class FString                                 HlslId;                                            // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   PinName;                                           // 0x0080(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UOptimusValueContainer*                 DefaultValue;                                      // 0x0090(0x0008)(ZeroConstructor, Deprecated, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate, TObjectPtr)
};

// ScriptStruct OptimusCore.OptimusAnimAttributeArray
// 0x0010 (0x0010 - 0x0000)
struct FOptimusAnimAttributeArray
{
public:
	TArray<struct FOptimusAnimAttributeDescription> InnerArray;                                      // 0x0000(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusDebugDrawParameters
// 0x0014 (0x0014 - 0x0000)
struct FOptimusDebugDrawParameters
{
public:
	bool                                          bForceEnable;                                      // 0x0000(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         MaxLineCount;                                      // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MaxTriangleCount;                                  // 0x0008(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MaxCharacterCount;                                 // 0x000C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FontSize;                                          // 0x0010(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusGraphVariableDescription
// 0x0090 (0x0090 - 0x0000)
struct FOptimusGraphVariableDescription
{
public:
	class FString                                 Name;                                              // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FShaderValueTypeHandle                 ValueType;                                         // 0x0010(0x0008)(NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FOptimusValueIdentifier                ValueId;                                           // 0x0018(0x0010)(NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Offset;                                            // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<uint8>                                 Value;                                             // 0x0030(0x0010)(ZeroConstructor, Deprecated, NativeAccessSpecifierPublic)
	struct FShaderValueContainer                  ShaderValue;                                       // 0x0040(0x0020)(Deprecated, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UObject>                 SourceObject;                                      // 0x0060(0x0030)(Deprecated, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusNode_ComponentSource_DuplicationInfo
// 0x0018 (0x0018 - 0x0000)
struct FOptimusNode_ComponentSource_DuplicationInfo
{
public:
	class FName                                   BindingName;                                       // 0x0000(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UOptimusComponentSource>    ComponentType;                                     // 0x0010(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusSecondaryInputBindingsGroup
// 0x0020 (0x0020 - 0x0000)
struct FOptimusSecondaryInputBindingsGroup
{
public:
	struct FOptimusValidatedName                  GroupName;                                         // 0x0000(0x000C)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOptimusParameterBindingArray          BindingArray;                                      // 0x0010(0x0010)(Edit, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusNode_GetVariable_DuplicationInfo
// 0x0060 (0x0060 - 0x0000)
struct FOptimusNode_GetVariable_DuplicationInfo
{
public:
	class FName                                   VariableName;                                      // 0x0000(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOptimusDataTypeRef                    DataType;                                          // 0x0010(0x0040)(NativeAccessSpecifierPublic)
	class FString                                 DefaultValue;                                      // 0x0050(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusPinPairInfo
// 0x0020 (0x0020 - 0x0000)
struct FOptimusPinPairInfo
{
public:
	TArray<class FName>                           InputPinPath;                                      // 0x0000(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<class FName>                           OutputPinPath;                                     // 0x0010(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusLoopTerminalInfo
// 0x0018 (0x0018 - 0x0000)
struct FOptimusLoopTerminalInfo
{
public:
	int32                                         Count;                                             // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOptimusParameterBindingArray          Bindings;                                          // 0x0008(0x0010)(Edit, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusNode_ResourceAccessorBase_DuplicationInfo
// 0x0090 (0x0090 - 0x0000)
struct FOptimusNode_ResourceAccessorBase_DuplicationInfo
{
public:
	class FName                                   ResourceName;                                      // 0x0000(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOptimusDataTypeRef                    DataType;                                          // 0x0010(0x0040)(NativeAccessSpecifierPublic)
	struct FOptimusDataDomain                     DataDomain;                                        // 0x0050(0x0040)(NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusDataType
// 0x0058 (0x0058 - 0x0000)
struct FOptimusDataType
{
public:
	class FName                                   TypeName;                                          // 0x0000(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   DisplayName;                                       // 0x0010(0x0010)(NativeAccessSpecifierPublic)
	struct FShaderValueTypeHandle                 ShaderValueType;                                   // 0x0020(0x0008)(NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ShaderValueSize;                                   // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   TypeCategory;                                      // 0x002C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TWeakObjectPtr<class UObject>                 TypeObject;                                        // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHasCustomPinColor;                                // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CustomPinColor;                                    // 0x0044(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOptimusDataTypeUsageFlags                    UsageFlags;                                        // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOptimusDataTypeFlags                         TypeFlags;                                         // 0x0055(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_56[0x2];                                       // 0x0056(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct OptimusCore.OptimusComputeGraphInfo
// 0x0018 (0x0018 - 0x0000)
struct FOptimusComputeGraphInfo
{
public:
	EOptimusNodeGraphType                         GraphType;                                         // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   GraphName;                                         // 0x0004(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UOptimusComputeGraph*                   ComputeGraph;                                      // 0x0010(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
};

// ScriptStruct OptimusCore.OptimusDeformerInstanceExecInfo
// 0x0030 (0x0030 - 0x0000)
struct FOptimusDeformerInstanceExecInfo
{
public:
	class FName                                   GraphName;                                         // 0x0000(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOptimusNodeGraphType                         GraphType;                                         // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UComputeGraph*                          ComputeGraph;                                      // 0x0010(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	struct FComputeGraphInstance                  ComputeGraphInstance;                              // 0x0018(0x0018)(NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusDeformerInstanceComponentBinding
// 0x0018 (0x0018 - 0x0000)
struct FOptimusDeformerInstanceComponentBinding
{
public:
	class FName                                   ProviderName;                                      // 0x0000(0x000C)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ComponentName;                                     // 0x000C(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusExecutionDomain
// 0x0020 (0x0020 - 0x0000)
struct FOptimusExecutionDomain
{
public:
	EOptimusExecutionDomainType                   Type;                                              // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class FName                                   Name;                                              // 0x0004(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class FString                                 Expression;                                        // 0x0010(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
};

// ScriptStruct OptimusCore.OptimusFunctionNodeGraphHeader
// 0x0048 (0x0048 - 0x0000)
struct FOptimusFunctionNodeGraphHeader
{
public:
	TSoftObjectPtr<class UOptimusFunctionNodeGraph> GraphPath;                                       // 0x0000(0x0030)(UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   FunctionName;                                      // 0x0030(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   Category;                                          // 0x003C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusFunctionNodeGraphHeaderArray
// 0x0010 (0x0010 - 0x0000)
struct FOptimusFunctionNodeGraphHeaderArray
{
public:
	TArray<struct FOptimusFunctionNodeGraphHeader> Headers;                                          // 0x0000(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusFunctionReferenceNodeSet
// 0x0050 (0x0050 - 0x0000)
struct FOptimusFunctionReferenceNodeSet
{
public:
	TSet<TSoftObjectPtr<class UOptimusNode_FunctionReference>> Nodes;                                // 0x0000(0x0050)(UObjectWrapper, NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusFunctionReferenceData
// 0x0050 (0x0050 - 0x0000)
struct FOptimusFunctionReferenceData
{
public:
	TMap<struct FSoftObjectPath, struct FOptimusFunctionReferenceNodeSet> FunctionReferences;        // 0x0000(0x0050)(NativeAccessSpecifierPublic)
};

// ScriptStruct OptimusCore.OptimusVariableMetaDataEntry
// 0x0020 (0x0020 - 0x0000)
struct FOptimusVariableMetaDataEntry
{
public:
	class FName                                   Key;                                               // 0x0000(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Value;                                             // 0x0010(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

SDK_NAMESPACE_END
