#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: R_Fort_Detective_Office

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function R_Fort_Detective_Office.R_Fort_Detective_Office_C.BndEvt__R_Fort_ChiefPolice_Office_BP_InstantLoot_Money_03_2_K2Node_ActorBoundEvent_11_SBZLootedSignature__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct R_Fort_Detective_Office_C_BndEvt__R_Fort_ChiefPolice_Office_BP_InstantLoot_Money_03_2_K2Node_ActorBoundEvent_11_SBZLootedSignature__DelegateSignature final
{
public:
	class ASBZInstantLoot*                        InstantLoot;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASBZPlayerCharacter*                    TakenByPlayer;                                     // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// Function R_Fort_Detective_Office.R_Fort_Detective_Office_C.BndEvt__R_Fort_ChiefPolice_Office_BP_InstantLoot_Money_2_K2Node_ActorBoundEvent_8_SBZLootedSignature__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct R_Fort_Detective_Office_C_BndEvt__R_Fort_ChiefPolice_Office_BP_InstantLoot_Money_2_K2Node_ActorBoundEvent_8_SBZLootedSignature__DelegateSignature final
{
public:
	class ASBZInstantLoot*                        InstantLoot;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASBZPlayerCharacter*                    TakenByPlayer;                                     // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// Function R_Fort_Detective_Office.R_Fort_Detective_Office_C.BndEvt__R_Fort_ChiefPolice_Office_BP_InstantLoot_Money_3_K2Node_ActorBoundEvent_9_SBZLootedSignature__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct R_Fort_Detective_Office_C_BndEvt__R_Fort_ChiefPolice_Office_BP_InstantLoot_Money_3_K2Node_ActorBoundEvent_9_SBZLootedSignature__DelegateSignature final
{
public:
	class ASBZInstantLoot*                        InstantLoot;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASBZPlayerCharacter*                    TakenByPlayer;                                     // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// Function R_Fort_Detective_Office.R_Fort_Detective_Office_C.BndEvt__R_Fort_ChiefPolice_Office_BP_InstantLoot_Money_4_K2Node_ActorBoundEvent_12_SBZLootedSignature__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct R_Fort_Detective_Office_C_BndEvt__R_Fort_ChiefPolice_Office_BP_InstantLoot_Money_4_K2Node_ActorBoundEvent_12_SBZLootedSignature__DelegateSignature final
{
public:
	class ASBZInstantLoot*                        InstantLoot;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASBZPlayerCharacter*                    TakenByPlayer;                                     // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// Function R_Fort_Detective_Office.R_Fort_Detective_Office_C.BndEvt__R_Fort_Detective_Office_SBZPlayerTriggerVolume_PlayerNearAnderssonLocker1_K2Node_ActorBoundEvent_0_SBZPawnDynamicDelegate__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct R_Fort_Detective_Office_C_BndEvt__R_Fort_Detective_Office_SBZPlayerTriggerVolume_PlayerNearAnderssonLocker1_K2Node_ActorBoundEvent_0_SBZPawnDynamicDelegate__DelegateSignature final
{
public:
	class APawn*                                  Pawn;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// Function R_Fort_Detective_Office.R_Fort_Detective_Office_C.ExecuteUbergraph_R_Fort_Detective_Office
// 0x00D0 (0x00D0 - 0x0000)
struct R_Fort_Detective_Office_C_ExecuteUbergraph_R_Fort_Detective_Office final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  K2Node_ActorBoundEvent_Pawn;                       // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_RemoteEvent_ReturnValue;                  // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_RemoteEvent_ReturnValue_1;                // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         CallFunc_DestroyActors_KeptActors;                 // 0x0018(0x0010)(ReferenceParm)
	TArray<class AActor*>                         CallFunc_DestroyActors_DestroyedActors;            // 0x0028(0x0010)(ReferenceParm)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ASBZInstantLoot*                        K2Node_ActorBoundEvent_InstantLoot_3;              // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASBZPlayerCharacter*                    K2Node_ActorBoundEvent_TakenByPlayer_3;            // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASBZInstantLoot*                        K2Node_ActorBoundEvent_InstantLoot_2;              // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASBZPlayerCharacter*                    K2Node_ActorBoundEvent_TakenByPlayer_2;            // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASBZInstantLoot*                        K2Node_ActorBoundEvent_InstantLoot_1;              // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASBZPlayerCharacter*                    K2Node_ActorBoundEvent_TakenByPlayer_1;            // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASBZInstantLoot*                        K2Node_ActorBoundEvent_InstantLoot;                // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASBZPlayerCharacter*                    K2Node_ActorBoundEvent_TakenByPlayer;              // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASBZPlayerCharacter*                    CallFunc_GetClosestPlayerToActor_PlayerCharacter;  // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetClosestPlayerToActor_Distance;         // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         CallFunc_DestroyActors_KeptActors_1;               // 0x0090(0x0010)(ReferenceParm)
	TArray<class AActor*>                         CallFunc_DestroyActors_DestroyedActors_1;          // 0x00A0(0x0010)(ReferenceParm)
	TArray<class AActor*>                         CallFunc_DestroyActors_KeptActors_2;               // 0x00B0(0x0010)(ReferenceParm)
	TArray<class AActor*>                         CallFunc_DestroyActors_DestroyedActors_2;          // 0x00C0(0x0010)(ReferenceParm)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
