#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SHI_BPL_Fluorescent_Hanging_01

#include "Basic.hpp"

#include "Enum_LampStages_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass SHI_BPL_Fluorescent_Hanging_01.SHI_BPL_Fluorescent_Hanging_01_C
// 0x0028 (0x0350 - 0x0328)
class ASHI_BPL_Fluorescent_Hanging_01_C final : public AActor
{
public:
	class UStaticMeshComponent*                   LGT_Fluorescent_02_Cable;                          // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight;                                         // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LGT_Fluorescent_02;                                // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	Enum_LampStages                               States;                                            // 0x0348(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SHI_BPL_Fluorescent_Hanging_01_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SHI_BPL_Fluorescent_Hanging_01_C")
	}
	static class ASHI_BPL_Fluorescent_Hanging_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASHI_BPL_Fluorescent_Hanging_01_C>();
	}
};

SDK_NAMESPACE_END
