#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SHI_BPL_Hallogen_Pannel_01

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"
#include "Enum_LampStages_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass SHI_BPL_Hallogen_Pannel_01.SHI_BPL_Hallogen_Pannel_01_C
// 0x0028 (0x0398 - 0x0370)
class ASHI_BPL_Hallogen_Pannel_01_C final : public ASBZReplicatedIntStateActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USpotLightComponent*                    SpotLight;                                         // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LGT_WallLampIndustrial_01_B;                       // 0x0380(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	Enum_LampStages                               States;                                            // 0x0390(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_SHI_BPL_Hallogen_Pannel_01(int32 EntryPoint);
	void OnStateChanged(int32 OldState, int32 NewState, bool bDoCosmetics);
	void SetStateFunction(Enum_LampStages State_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SHI_BPL_Hallogen_Pannel_01_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SHI_BPL_Hallogen_Pannel_01_C")
	}
	static class ASHI_BPL_Hallogen_Pannel_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASHI_BPL_Hallogen_Pannel_01_C>();
	}
};

SDK_NAMESPACE_END
