#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Stonk_BPL_Square_Square_Warm

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Stonk_BPL_Square_Square_Warm.Stonk_BPL_Square_Square_Warm_C
// 0x0030 (0x0358 - 0x0328)
class AStonk_BPL_Square_Square_Warm_C final : public AActor
{
public:
	class URectLightComponent*                    RectLight;                                         // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Int_SHE_Modern_01_Ceil_02_96x48_Lamp_01_A_3;       // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Int_SHE_Modern_01_Ceil_02_96x48_Lamp_01_A_2;       // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Int_SHE_Modern_01_Ceil_02_96x48_Lamp_01_A_1;       // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Int_SHE_Modern_01_Ceil_02_96x48_Lamp_01_A;         // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Stonk_BPL_Square_Square_Warm_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Stonk_BPL_Square_Square_Warm_C")
	}
	static class AStonk_BPL_Square_Square_Warm_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AStonk_BPL_Square_Square_Warm_C>();
	}
};

SDK_NAMESPACE_END
