#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Inventory_LoadoutSkillsButton_Class

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_UI_Inventory_LoadoutSkillsButton_Class.WBP_UI_Inventory_LoadoutSkillsButton_Class_C.ExecuteUbergraph_WBP_UI_Inventory_LoadoutSkillsButton_Class
// 0x0018 (0x0018 - 0x0000)
struct WBP_UI_Inventory_LoadoutSkillsButton_Class_C_ExecuteUbergraph_WBP_UI_Inventory_LoadoutSkillsButton_Class
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0008(0x0010)()
};

// Function WBP_UI_Inventory_LoadoutSkillsButton_Class.WBP_UI_Inventory_LoadoutSkillsButton_Class_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_UI_Inventory_LoadoutSkillsButton_Class_C_PreConstruct
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
