#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_STO_ControlScreenIdle

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_STO_ControlScreenIdle.WBP_STO_ControlScreenIdle_C
// 0x0008 (0x02F8 - 0x02F0)
class UWBP_STO_ControlScreenIdle_C final : public UUserWidget
{
public:
	class UImage*                                 Image;                                             // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_STO_ControlScreenIdle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_STO_ControlScreenIdle_C")
	}
	static class UWBP_STO_ControlScreenIdle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_STO_ControlScreenIdle_C>();
	}
};

SDK_NAMESPACE_END
