#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Widget_PartyMemberWeaponStatus

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "Starbreeze_structs.hpp"
#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_UI_Widget_PartyMemberWeaponStatus.WBP_UI_Widget_PartyMemberWeaponStatus_C
// 0x0078 (0x0398 - 0x0320)
class UWBP_UI_Widget_PartyMemberWeaponStatus_C : public UPD3WeaponStatusWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0320(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       OnPickUpAnimation;                                 // 0x0328(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Background_I;                                      // 0x0330(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_AmmoBag;                                      // 0x0338(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_AmmoBagBackground;                            // 0x0340(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FSlateColor                            NormalTextColor;                                   // 0x0348(0x0014)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance)
	struct FSlateColor                            LowTextColor;                                      // 0x035C(0x0014)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance)
	struct FSlateColor                            CriticalTextColor;                                 // 0x0370(0x0014)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance)
	uint8                                         Pad_384[0x4];                                      // 0x0384(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        EquippedOpacity;                                   // 0x0388(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        UnequippedOpacity;                                 // 0x0390(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_UI_Widget_PartyMemberWeaponStatus(int32 EntryPoint);
	void OnAmmoAdded(int32 AmmoAddedCount, bool bIsFireRangedWeaponScope);
	void OnAmmoTotalChanged(int32 AmmoTotalChanged);
	void OnAmmoTotalStateChanged(EPD3AmmoState NewState);
	void OnEquippedChanged(bool bIsEquippedNewValue);
	void OnInitialized();
	void SetAmmoState(class UTextBlock* TextBlock, EPD3AmmoState Index_0);
	void SetEquipped(bool IsEquipped);
	void SetText(int32 AmmoValue);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UI_Widget_PartyMemberWeaponStatus_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UI_Widget_PartyMemberWeaponStatus_C")
	}
	static class UWBP_UI_Widget_PartyMemberWeaponStatus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UI_Widget_PartyMemberWeaponStatus_C>();
	}
};

SDK_NAMESPACE_END
