#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Widget_PartyMemberRevive

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_UI_Widget_PartyMemberRevive.WBP_UI_Widget_PartyMemberRevive_C
// 0x0038 (0x0350 - 0x0318)
class UWBP_UI_Widget_PartyMemberRevive_C final : public UPD3ReviveInteractionWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0318(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_ReviveGauge;                                 // 0x0320(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               ReviveGauge_Material;                              // 0x0328(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnReviveStartedDispatcher;                         // 0x0330(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              OnReviveEndedDispatcher;                           // 0x0340(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void Construct();
	void ExecuteUbergraph_WBP_UI_Widget_PartyMemberRevive(int32 EntryPoint);
	void OnReviveInteractionEnded();
	void OnReviveInteractionStarted();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UI_Widget_PartyMemberRevive_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UI_Widget_PartyMemberRevive_C")
	}
	static class UWBP_UI_Widget_PartyMemberRevive_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UI_Widget_PartyMemberRevive_C>();
	}
};
DUMPER7_ASSERTS_UWBP_UI_Widget_PartyMemberRevive_C;

SDK_NAMESPACE_END
