#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_StonkBase

#include "Basic.hpp"

#include "WBP_StonkBase_classes.hpp"
#include "WBP_StonkBase_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_StonkBase.WBP_StonkBase_C.Active
// (BlueprintCallable, BlueprintEvent)

void UWBP_StonkBase_C::Active()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "Active");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_StonkBase.WBP_StonkBase_C.Code
// (BlueprintCallable, BlueprintEvent)

void UWBP_StonkBase_C::Code()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "Code");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_StonkBase.WBP_StonkBase_C.Done
// (BlueprintCallable, BlueprintEvent)

void UWBP_StonkBase_C::Done()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "Done");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_StonkBase.WBP_StonkBase_C.Email
// (BlueprintCallable, BlueprintEvent)

void UWBP_StonkBase_C::Email()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "Email");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_StonkBase.WBP_StonkBase_C.ExecuteUbergraph_WBP_StonkBase
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_StonkBase_C::ExecuteUbergraph_WBP_StonkBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "ExecuteUbergraph_WBP_StonkBase");

	Params::WBP_StonkBase_C_ExecuteUbergraph_WBP_StonkBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_StonkBase.WBP_StonkBase_C.Failed
// (BlueprintCallable, BlueprintEvent)

void UWBP_StonkBase_C::Failed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "Failed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_StonkBase.WBP_StonkBase_C.HideAllWidgetsButOne
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          WidgetToShow                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_StonkBase_C::HideAllWidgetsButOne(class UWidget* WidgetToShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "HideAllWidgetsButOne");

	Params::WBP_StonkBase_C_HideAllWidgetsButOne Parms{};

	Parms.WidgetToShow = WidgetToShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_StonkBase.WBP_StonkBase_C.Interupted
// (BlueprintCallable, BlueprintEvent)

void UWBP_StonkBase_C::Interupted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "Interupted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_StonkBase.WBP_StonkBase_C.Names
// (BlueprintCallable, BlueprintEvent)

void UWBP_StonkBase_C::Names()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "Names");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_StonkBase.WBP_StonkBase_C.NotActive
// (BlueprintCallable, BlueprintEvent)

void UWBP_StonkBase_C::NotActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "NotActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_StonkBase.WBP_StonkBase_C.Progressing
// (BlueprintCallable, BlueprintEvent)

void UWBP_StonkBase_C::Progressing()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "Progressing");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_StonkBase.WBP_StonkBase_C.Unlocked
// (BlueprintCallable, BlueprintEvent)

void UWBP_StonkBase_C::Unlocked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "Unlocked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_StonkBase.WBP_StonkBase_C.UpdateEmailDisplayText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FSBZHackableDisplayText&   DisplayText                                            (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_StonkBase_C::UpdateEmailDisplayText(const struct FSBZHackableDisplayText& DisplayText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "UpdateEmailDisplayText");

	Params::WBP_StonkBase_C_UpdateEmailDisplayText Parms{};

	Parms.DisplayText = std::move(DisplayText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_StonkBase.WBP_StonkBase_C.updateHackingProgress
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   progress                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_StonkBase_C::updateHackingProgress(int32 progress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "updateHackingProgress");

	Params::WBP_StonkBase_C_updateHackingProgress Parms{};

	Parms.progress = progress;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_StonkBase.WBP_StonkBase_C.updateHackingTimerProcessName
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_StonkBase_C::updateHackingTimerProcessName(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "updateHackingTimerProcessName");

	Params::WBP_StonkBase_C_updateHackingTimerProcessName Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_StonkBase.WBP_StonkBase_C.updateInformation
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      main                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// const class FText&                      secondary                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)
// const class FText&                      additional                                             (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_StonkBase_C::updateInformation(const class FText& main, const class FText& secondary, const class FText& additional)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "updateInformation");

	Params::WBP_StonkBase_C_updateInformation Parms{};

	Parms.main = std::move(main);
	Parms.secondary = std::move(secondary);
	Parms.additional = std::move(additional);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_StonkBase.WBP_StonkBase_C.updateKeypadPossibleCodes
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<int32>&                    codes                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_StonkBase_C::updateKeypadPossibleCodes(const TArray<int32>& codes)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "updateKeypadPossibleCodes");

	Params::WBP_StonkBase_C_updateKeypadPossibleCodes Parms{};

	Parms.codes = std::move(codes);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_StonkBase.WBP_StonkBase_C.UpdateSuccessText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_StonkBase_C::UpdateSuccessText(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "UpdateSuccessText");

	Params::WBP_StonkBase_C_UpdateSuccessText Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_StonkBase.WBP_StonkBase_C.UpdateUnlockDisplayText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FSBZHackableDisplayText&   NewDisplayText                                         (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_StonkBase_C::UpdateUnlockDisplayText(const struct FSBZHackableDisplayText& NewDisplayText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StonkBase_C", "UpdateUnlockDisplayText");

	Params::WBP_StonkBase_C_UpdateUnlockDisplayText Parms{};

	Parms.NewDisplayText = std::move(NewDisplayText);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
