#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InteractableControlPanelOpen

#include "Basic.hpp"

#include "WBP_InteractableControlPanelOpen_classes.hpp"
#include "WBP_InteractableControlPanelOpen_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_InteractableControlPanelOpen.WBP_InteractableControlPanelOpen_C.ExecuteUbergraph_WBP_InteractableControlPanelOpen
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InteractableControlPanelOpen_C::ExecuteUbergraph_WBP_InteractableControlPanelOpen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InteractableControlPanelOpen_C", "ExecuteUbergraph_WBP_InteractableControlPanelOpen");

	Params::WBP_InteractableControlPanelOpen_C_ExecuteUbergraph_WBP_InteractableControlPanelOpen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InteractableControlPanelOpen.WBP_InteractableControlPanelOpen_C.SetRoom
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      RoomName                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_InteractableControlPanelOpen_C::SetRoom(const class FText& RoomName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InteractableControlPanelOpen_C", "SetRoom");

	Params::WBP_InteractableControlPanelOpen_C_SetRoom Parms{};

	Parms.RoomName = std::move(RoomName);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
