#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Inventory_LoadoutEmotesButton

#include "Basic.hpp"

#include "WBP_UI_Inventory_LoadoutEmotesButton_classes.hpp"
#include "WBP_UI_Inventory_LoadoutEmotesButton_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_UI_Inventory_LoadoutEmotesButton.WBP_UI_Inventory_LoadoutEmotesButton_C.ButtonFocusedChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInHasFocus                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Inventory_LoadoutEmotesButton_C::ButtonFocusedChanged(bool bInHasFocus)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Inventory_LoadoutEmotesButton_C", "ButtonFocusedChanged");

	Params::WBP_UI_Inventory_LoadoutEmotesButton_C_ButtonFocusedChanged Parms{};

	Parms.bInHasFocus = bInHasFocus;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Inventory_LoadoutEmotesButton.WBP_UI_Inventory_LoadoutEmotesButton_C.ButtonHoveredChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInIsHovered                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Inventory_LoadoutEmotesButton_C::ButtonHoveredChanged(bool bInIsHovered)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Inventory_LoadoutEmotesButton_C", "ButtonHoveredChanged");

	Params::WBP_UI_Inventory_LoadoutEmotesButton_C_ButtonHoveredChanged Parms{};

	Parms.bInIsHovered = bInIsHovered;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Inventory_LoadoutEmotesButton.WBP_UI_Inventory_LoadoutEmotesButton_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UI_Inventory_LoadoutEmotesButton_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Inventory_LoadoutEmotesButton_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_Inventory_LoadoutEmotesButton.WBP_UI_Inventory_LoadoutEmotesButton_C.Create Emote Icons Button
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_UI_Inventory_LoadoutEmotesButton_C::Create_Emote_Icons_Button()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Inventory_LoadoutEmotesButton_C", "Create Emote Icons Button");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_Inventory_LoadoutEmotesButton.WBP_UI_Inventory_LoadoutEmotesButton_C.ExecuteUbergraph_WBP_UI_Inventory_LoadoutEmotesButton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Inventory_LoadoutEmotesButton_C::ExecuteUbergraph_WBP_UI_Inventory_LoadoutEmotesButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Inventory_LoadoutEmotesButton_C", "ExecuteUbergraph_WBP_UI_Inventory_LoadoutEmotesButton");

	Params::WBP_UI_Inventory_LoadoutEmotesButton_C_ExecuteUbergraph_WBP_UI_Inventory_LoadoutEmotesButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Inventory_LoadoutEmotesButton.WBP_UI_Inventory_LoadoutEmotesButton_C.OnFocused
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsFocused                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Inventory_LoadoutEmotesButton_C::OnFocused(bool bIsFocused)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Inventory_LoadoutEmotesButton_C", "OnFocused");

	Params::WBP_UI_Inventory_LoadoutEmotesButton_C_OnFocused Parms{};

	Parms.bIsFocused = bIsFocused;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Inventory_LoadoutEmotesButton.WBP_UI_Inventory_LoadoutEmotesButton_C.OnHover
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsHovered                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Inventory_LoadoutEmotesButton_C::OnHover(bool bIsHovered)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Inventory_LoadoutEmotesButton_C", "OnHover");

	Params::WBP_UI_Inventory_LoadoutEmotesButton_C_OnHover Parms{};

	Parms.bIsHovered = bIsHovered;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Inventory_LoadoutEmotesButton.WBP_UI_Inventory_LoadoutEmotesButton_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UI_Inventory_LoadoutEmotesButton_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Inventory_LoadoutEmotesButton_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_Inventory_LoadoutEmotesButton.WBP_UI_Inventory_LoadoutEmotesButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Inventory_LoadoutEmotesButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Inventory_LoadoutEmotesButton_C", "PreConstruct");

	Params::WBP_UI_Inventory_LoadoutEmotesButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Inventory_LoadoutEmotesButton.WBP_UI_Inventory_LoadoutEmotesButton_C.RefreshVisuals
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_UI_Inventory_LoadoutEmotesButton_C::RefreshVisuals()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Inventory_LoadoutEmotesButton_C", "RefreshVisuals");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_Inventory_LoadoutEmotesButton.WBP_UI_Inventory_LoadoutEmotesButton_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_Inventory_LoadoutEmotesButton_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Inventory_LoadoutEmotesButton_C", "Tick");

	Params::WBP_UI_Inventory_LoadoutEmotesButton_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_Inventory_LoadoutEmotesButton.WBP_UI_Inventory_LoadoutEmotesButton_C.UpdateEmoteButton
// (BlueprintCallable, BlueprintEvent)

void UWBP_UI_Inventory_LoadoutEmotesButton_C::UpdateEmoteButton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_Inventory_LoadoutEmotesButton_C", "UpdateEmoteButton");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
