#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ItemInventoryDescription

#include "Basic.hpp"

#include "WBP_ItemInventoryDescription_classes.hpp"
#include "WBP_ItemInventoryDescription_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_ItemInventoryDescription.WBP_ItemInventoryDescription_C.ExecuteUbergraph_WBP_ItemInventoryDescription
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemInventoryDescription_C::ExecuteUbergraph_WBP_ItemInventoryDescription(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInventoryDescription_C", "ExecuteUbergraph_WBP_ItemInventoryDescription");

	Params::WBP_ItemInventoryDescription_C_ExecuteUbergraph_WBP_ItemInventoryDescription Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemInventoryDescription.WBP_ItemInventoryDescription_C.GetEquippableConfig
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USBZInventoryItemDecorator*       ItemDeco                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class USBZBaseWeaponData**              BaseWeaponData                                         (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FSBZEquippableConfig*            EquippableConfig                                       (ConstParm, Parm, OutParm)
// bool*                                   bIsPreset                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemInventoryDescription_C::GetEquippableConfig(class USBZInventoryItemDecorator* ItemDeco, class USBZBaseWeaponData** BaseWeaponData, struct FSBZEquippableConfig* EquippableConfig, bool* bIsPreset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInventoryDescription_C", "GetEquippableConfig");

	Params::WBP_ItemInventoryDescription_C_GetEquippableConfig Parms{};

	Parms.ItemDeco = ItemDeco;

	UObject::ProcessEvent(Func, &Parms);

	if (BaseWeaponData != nullptr)
		*BaseWeaponData = Parms.BaseWeaponData;

	if (EquippableConfig != nullptr)
		*EquippableConfig = std::move(Parms.EquippableConfig);

	if (bIsPreset != nullptr)
		*bIsPreset = Parms.bIsPreset;
}


// Function WBP_ItemInventoryDescription.WBP_ItemInventoryDescription_C.InitGenericData
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class USBZInventoryItemDecorator*       ItemDeco                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemInventoryDescription_C::InitGenericData(class USBZInventoryItemDecorator* ItemDeco)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInventoryDescription_C", "InitGenericData");

	Params::WBP_ItemInventoryDescription_C_InitGenericData Parms{};

	Parms.ItemDeco = ItemDeco;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemInventoryDescription.WBP_ItemInventoryDescription_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemInventoryDescription_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInventoryDescription_C", "PreConstruct");

	Params::WBP_ItemInventoryDescription_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemInventoryDescription.WBP_ItemInventoryDescription_C.RefreshNamedSlotVisibility
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_ItemInventoryDescription_C::RefreshNamedSlotVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInventoryDescription_C", "RefreshNamedSlotVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemInventoryDescription.WBP_ItemInventoryDescription_C.SetItemDecorator
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class USBZInventoryItemDecorator*       ItemDeco                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemInventoryDescription_C::SetItemDecorator(class USBZInventoryItemDecorator* ItemDeco)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInventoryDescription_C", "SetItemDecorator");

	Params::WBP_ItemInventoryDescription_C_SetItemDecorator Parms{};

	Parms.ItemDeco = ItemDeco;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemInventoryDescription.WBP_ItemInventoryDescription_C.TryInitArmorData
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class USBZInventoryItemDecorator*       ItemDeco                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemInventoryDescription_C::TryInitArmorData(class USBZInventoryItemDecorator* ItemDeco)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInventoryDescription_C", "TryInitArmorData");

	Params::WBP_ItemInventoryDescription_C_TryInitArmorData Parms{};

	Parms.ItemDeco = ItemDeco;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemInventoryDescription.WBP_ItemInventoryDescription_C.TryInitWeaponData
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USBZInventoryItemDecorator*       ItemDeco                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemInventoryDescription_C::TryInitWeaponData(class USBZInventoryItemDecorator* ItemDeco)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInventoryDescription_C", "TryInitWeaponData");

	Params::WBP_ItemInventoryDescription_C_TryInitWeaponData Parms{};

	Parms.ItemDeco = ItemDeco;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemInventoryDescription.WBP_ItemInventoryDescription_C.TryInitWeaponSlots
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USBZInventoryItemDecorator*       ItemDeco                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemInventoryDescription_C::TryInitWeaponSlots(class USBZInventoryItemDecorator* ItemDeco)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInventoryDescription_C", "TryInitWeaponSlots");

	Params::WBP_ItemInventoryDescription_C_TryInitWeaponSlots Parms{};

	Parms.ItemDeco = ItemDeco;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
